---
    macaddrs:
      b8:27:eb:d6:16:38:
            hostname: "worker1"
            domain: "local"
            locale: "en_US.UTF-8"
            timezone: "America/New_York"
            xkblayout: "us"
            wifi_country: "US"
            enable_gui: False
            enable_autologin: False
            enable_bootwait: False
            enable_bootsplash: False
            enable_camera: False
            enable_vnc: False
            enable_spi: False
            enable_i2c: False
            enable_serial: False
            enable_serial_hw: False
            enable_onewire: False
            enable_rgpio: False
            darshan_dev: False
            extra_software:
              - "libglib2.0-dev"
      b8:27:eb:4d:84:ac:
            hostname: "worker2"
            domain: "local"
            locale: "en_US.UTF-8"
            timezone: "America/New_York"
            xkblayout: "us"
            wifi_country: "US"
            enable_gui: False
            enable_autologin: False
            enable_bootwait: False
            enable_bootsplash: False
            enable_camera: False
            enable_vnc: False
            enable_spi: False
            enable_i2c: False
            enable_serial: False
            enable_serial_hw: False
            enable_onewire: False
            enable_rgpio: False
            darshan_dev: False
            extra_software:
              - "libglib2.0-dev"
      b8:27:eb:22:8f:9e:
            hostname: "worker3"
            domain: "local"
            locale: "en_US.UTF-8"
            timezone: "America/New_York"
            xkblayout: "us"
            wifi_country: "US"
            enable_gui: False
            enable_autologin: False
            enable_bootwait: False
            enable_bootsplash: False
            enable_camera: False
            enable_vnc: False
            enable_spi: False
            enable_i2c: False
            enable_serial: False
            enable_serial_hw: False
            enable_onewire: False
            enable_rgpio: False
            darshan_dev: False
            extra_software:
              - "libglib2.0-dev"  
      b8:27:eb:45:b6:64:
            hostname: "worker4"
            domain: "local"
            locale: "en_US.UTF-8"
            timezone: "America/New_York"
            xkblayout: "us"
            wifi_country: "US"
            enable_gui: False
            enable_autologin: False
            enable_bootwait: False
            enable_bootsplash: False
            enable_camera: False
            enable_vnc: False
            enable_spi: False
            enable_i2c: False
            enable_serial: False
            enable_serial_hw: False
            enable_onewire: False
            enable_rgpio: False
            darshan_dev: False
            extra_software:
              - "libglib2.0-dev"                     
        b8:27:eb:f4:8a:9f:
            hostname: "leader"
            domain: "local"
            locale: "en_US.UTF-8"
            timezone: "America/New_York"
            xkblayout: "us"
            wifi_country: "US"
            enable_gui: True
            enable_autologin: False
            enable_bootwait: False
            enable_bootsplash: False
            enable_camera: False
            enable_vnc: True
            enable_spi: False
            enable_i2c: False
            enable_serial: False
            enable_serial_hw: False
            enable_onewire: False
            enable_rgpio: False
            darshan_dev: False
            extra_software:
              - "libglib2.0-dev"
